Level 2
AliceHab/movies-explorer-frontendd pull request #1
Opened 2023-09-20 12:49 UTC by AliceHab

Подготовлен фронтенд

2023-09-20 13:54 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- Контент тянется на весь экран на больших мониторах, хорошо бы добавить ему фиксацию по макету (1280) и центрировать относительно вьюпорта. В этом могут помочь сво-ва max-width, margin.

	**Главная**
	- 768 https://yadi.sk/d/YmYUZML9qIAvNg https://yadi.sk/d/gpaUPi_5eyuONw параметры текста
	- 320 https://yadi.sk/d/x74lm7244iiLaQ https://yadi.sk/d/RvK2Vw40NNLQCQ параметры текста, https://yadi.sk/d/x74lm7244iiLaQ последовательность

	**Фильмы**
	- https://yadi.sk/d/a7nvP8wrPuKH5Q цвет текста меню белый
	- https://yadi.sk/d/bdfE0SN2mUce3Q при переполнении кнопку немного сжимает

	**Сохраненные**
	- Карточки с фильмами отличаются от макета (там кнопка удалить)
	- https://yadi.sk/i/WW_dtM_t1IKxHw - кнопки Еще не нужно, также отличается отступ до подвала на всех разрешениях.


- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

	- Стр. Вход/Регистрация/Профиль образуется прокрутка от 320 до 470пх примерно

- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- https://github.com/AliceHab/react-mesto-auth - ссылка ведет к ошибке 404 (возможно проект не открыт)
	- Страница Вход - ссылка Регистрация не актуализирована
	- Страница Вход/Регистрация - хорошо бы логотип сделать ссылкой, ведущей на главную
	- Выйти из профиля можно сделать переход на Главную/Логин

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/X0xWW_lV1mwsvw в проекте есть ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/
	- navtab, aboutme и по аналогии по всему проекту - при именовании классов придерживайтесь единой стилистики, так в большинстве случаев используется кебаб-кейс
	- about-project__first-part, header__link-to-main - смысловые одинаковые селекторы используют один класс, для отличий хорошо добавлять модификаторы БЭМ.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/JgcnXuahZ_NjDw https://yadi.sk/d/OKtRULnx-T53ug https://yadi.sk/d/QB2i1ZxS0NITJA https://yadi.sk/d/P4nThqe2BHr9HA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
	- контент следует сделать отзывчивым на всех устройствах (страницы прижимаются к верху на десктопах https://yadi.sk/d/HD2xApVf12Db7Q). Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, шапка прижата к верху, футер к низу. Можно лучше на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).
	- https://yadi.sk/d/4jYe6ZSYy-UXYw текст будет заходить за кнопку, можно добавить вн.отступ справа

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- Проект содержит ошибки валидации, воспользуйтесь валидатором для проверки https://validator.w3.org/#validate_by_input
	- Есть ошибки в консоли (стр. Вход/Рег/Фильмы/Профиль)
	- portfolio__arrow, promo__logo Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
	- aboutme__line, about-project__line, profile__border, search-form__bottom-line и т.к. по аналогии в проекте - также все стилизованные линии опишите без использования отдельного селектора.
	- aboutme__status - не по иерархии заголовок в секции
	- auth-form__title - нужен заголовок 1 уровня на каждой отдельной странице
	- auth-form, not-found - оформите селектором main главный контент на каждой странице (все кроме header и footer)
	- footer__copyrigth - нужен сем.заголовок по иерархии

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- header__button_type_account, header__button_type_account_active, header__nav - пересмотрите элементы в header т.к. вырывать из поточного режима крайне нежелательно, хорошо использовать технологию построения сетки

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

	- https://yadi.sk/d/1ilpnIli5txNcw Обратите внимание на страницу UI в макете Figma. На странице профиля следует использовать логику по макету. Изначально данные не доступны к изменению, после нажатия на Кнопку Редактировать состояние полей меняется, также нижняя панель с кнопками меняет свой вид. Также есть состояния ошибки (это можно заложить в верстку).

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- Лого - нет ховер эффекта
	- navtab - ссылки - нет ховер эффекта
	- aboutme__link, portfolio__link - нет ховер эффекта
	- ссылки в подвале - нет ховер эффекта
	- стр. Вход/Регистрация - кнопки/ссылки нет ховер эффекта (курсора)
	- Назад 404 - нет ховер эффекта
	- search-form__text-switch - оформите селектором label и при помощи атрибута for свяжите с чекбоксом, чтобы менял состояние при клике
	- Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.
	- Поиск нет ховера и курсора
	- Еще - нет ховер эффекта
	- Фильмы - кнопки нет ховер эффекта (таке добавьте одну карточку на стр.сФильмами с активной кнопкой, как в макете, если сделаете по щелчку - даже отлично)
	- Кнопки в Профиле - нет ховера

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face. [...]

2023-09-21 17:32 UTC, AliceHab commented
Добрый вечер! Спасибо за ревью

Хотел уточнить по ошибке валидатора wfd-id - https://disk.yandex.ru/i/ZPcqx4W8RHnaNg

В моем коде напрямую этот атрибут не указан. Подозреваю, что его автоматически генерирует пакет react-scroll для плавной прокрутки по якорным ссылкам. 

Могу ли я не исправлять эти ошибки? Или следует удалить плагин и переписать код в данной части

2023-09-23 06:02 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 2 ревью на Ваш проект. Хорошая работа по замечениям, уверена, что у Вас все получится.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	**Главная**
	- 320 https://yadi.sk/d/EhfcDJKNcAC5wA? https://yadi.sk/d/zB2aw6ETeagEEg, https://yadi.sk/d/x74lm7244iiLaQ последовательность

	**Сохраненные**
	- https://yadi.sk/d/mS95u1lBcQ640Q - отличается отступ до подвала на всех разрешениях.


- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/NOHT5cGRWye9sQ сохраняются ошибки БЭМ, воспользуйтесь валидатором для проверки https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/HqybKCGivyTkAg текст не должен здесь скрываться, т.к. он может быть изменен и посетители его должны прочитать - В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- about-me__line, about-project__line, profile__border, search-form__bottom-line и т.к. по аналогии в проекте - также все стилизованные линии опишите без использования отдельного селектора.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- header__nav - навигация вырвана из потока это нежелательное поведение, хорошо использовать технологию построения сетки, если пунктов меню будет больше, то все сломается

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- https://yadi.sk/d/hZimnIgTIF5yvg здесь у активной ссылки толщина 500 (Это хорошо реализуется при помощи добавления модификатора). -- Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Каждой форме добавьте атрибут name - Для тегов <form> так же следует заполнить атрибут name

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [ ] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.

	- https://yadi.sk/i/QmuuTXq9DVMpBw для каждого добавьте альт.шрифт

- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 67

2023-09-23 06:03 UTC, Savallera commented
> Добрый вечер! Спасибо за ревью
> 
> Хотел уточнить по ошибке валидатора wfd-id - https://disk.yandex.ru/i/ZPcqx4W8RHnaNg
> 
> В моем коде напрямую этот атрибут не указан. Подозреваю, что его автоматически генерирует пакет react-scroll для плавной прокрутки по якорным ссылкам.
> 
> Могу ли я не исправлять эти ошибки? Или следует удалить плагин и переписать код в данной части

Здравствуйте, да здесь все нормально, замечание по этой части удалено

2023-09-24 08:11 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Я Вас поздравляю, набранного балла достаточно, чтобы проект можно было принять. Желаю Вам дальнейших успехов и удачи во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/d/HqybKCGivyTkAg текст не должен здесь скрываться, т.к. он может быть изменен и посетители его должны прочитать - В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- about-me__line, about-project__line, profile__border и т.д. по аналогии в проекте - также все стилизованные линии опишите без использования отдельного селектора.

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

	- https://yadi.sk/d/hZimnIgTIF5yvg здесь у активной ссылки толщина 500 (Это хорошо реализуется при помощи добавления модификатора). -- Обратите внимание, что у активной вкладки на странице с фильмами/сохраненными фильмами дизайн немного отличается, она имеет отличную толщину шрифта. В мобильном меню активная вкладка всегда подчеркнута. Это можно сделать с помощью простых БЭМ модификаторов.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 91

2023-10-07 17:47 UTC, merged